### ISSUE TITLE
Icefilms does not play any video on 1.9.1

### ISSUE THREAD

**Issue by Kulendra** [Eldorados/eldorado-xbmc-addons#23]
Gives a script failed error. Following is the last part of the kodi.log

06:38:48 T:1657181248  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.8.3
06:38:48 T:1657181248  NOTICE: Icefilms: ----------------Icefilms Addon Param Info--------------------
06:38:48 T:1657181248  NOTICE: Icefilms: --- Version: 1.9.1
06:38:48 T:1657181248  NOTICE: Icefilms: --- Mode: 100
06:38:48 T:1657181248  NOTICE: Icefilms: --- DirMode:
06:38:48 T:1657181248  NOTICE: Icefilms: --- URL: http://www.icefilms.info/ip.php?v=132940&
06:38:48 T:1657181248  NOTICE: Icefilms: --- Video Type: movie
06:38:48 T:1657181248  NOTICE: Icefilms: --- Name: Limitless (2011) [COLOR red]*HD*[/COLOR]
06:38:48 T:1657181248  NOTICE: Icefilms: --- IMDB: tt1219289
06:38:48 T:1657181248  NOTICE: Icefilms: --- TMDB:
06:38:48 T:1657181248  NOTICE: Icefilms: --- Season:
06:38:48 T:1657181248  NOTICE: Icefilms: --- Episode:
06:38:48 T:1657181248  NOTICE: Icefilms: --- MyHandle: 14
06:38:48 T:1657181248  NOTICE: Icefilms: ---------------------------------------------------------------
06:38:48 T:1657181248  NOTICE: Icefilms: Loading sqlite3 as DB engine version: 3.8.8.3
06:38:51 T:1657181248  NOTICE: Icefilms: GetUrl: http://www.icefilms.info/ip.php?v=132940&
06:38:51 T:1657181248  NOTICE: Icefilms: params: None
06:38:51 T:1657181248  NOTICE: Icefilms: referrer: 'http://www.icefilms.info'
06:38:51 T:1657181248  NOTICE: Icefilms: cookie: False
06:38:51 T:1657181248  NOTICE: Icefilms: save_cookie: False
06:38:53 T:1657181248  NOTICE: Icefilms: GetUrl: http://www.icefilms.info/membersonly/component/com_iceplayer/video.php?h=331&w=719&vid=132940&img=
06:38:53 T:1657181248  NOTICE: Icefilms: params: None
06:38:53 T:1657181248  NOTICE: Icefilms: referrer: 'http://www.icefilms.info'
06:38:53 T:1657181248  NOTICE: Icefilms: cookie: False
06:38:53 T:1657181248  NOTICE: Icefilms: save_cookie: True
06:38:53 T:1657181248  NOTICE: Icefilms: Cookie saved
06:38:54 T:1657181248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.icefilms/default.py", line 3337, in <module>
                                                LOADMIRRORS(url)
                                              File "/storage/.kodi/addons/plugin.video.icefilms/default.py", line 1485, in LOADMIRRORS
                                                SOURCE(html, scrape, tag, ice_meta)
                                              File "/storage/.kodi/addons/plugin.video.icefilms/default.py", line 1606, in SOURCE
                                                args['sec'] = match.group(1) + match.group(2)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
06:38:54 T:1969324032   ERROR: GetDirectory - Error getting plugin://plugin.video.icefilms/?episode&imdbnum=tt1219289&mode=100&name=Limitless%20(2011)%20%5bCOLOR%20red%
06:38:54 T:1969324032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.icefilms/?episode&imdbnum=tt1219289&mode=100&name=Limitless%20(2011)%20%5bCOLOR%20red
06:38:56 T:1657181248  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by Kulendra** [comment]
I think we have a problem.
I printed the `page` variable to see where the problem was as line 1606 is simply grabbing the links. The page echoed this:

    <script type="text/javascript">
                                            //
                                            //
                                            // Hi,
                                            //    90% of our traffic is bots.
                                            //    The file hosts are complaining and shutting down.
                                            //    Ads are annoying, but necessary.
                                            //    Is a symbiosis not possible?
                                            //
                                            //    Continued scraper maintenance will lead to one 
                                            //    inevitable conclusion: the blacklisting of scraper
                                            //    users' IPs. This is the last thing anyone wants. 
                                            //    It is, therefore, in everyone's best interest 
                                            //    to discontinue maintaining icefilms scrapers. 
                                            //
                                            //     -ice admin
                                            //
                                            //

**Comment by Eldorados** [comment]
Well this kind of sucks... thanks!

**Comment by jbrouhard98** [comment]
so what, this means your iceflims plugin will no longer work ??

**Comment by Eldorados** [comment]
For now, any plugin for Icefilms won't work - it can be fixed, but they will start banning users' ip addresses

**Comment by wgc3rd** [comment]
is there a way to update the Icefilms Kodi addon, and disable any scraper, or fix any IP issue?

**Comment by Eldorados** [comment]
No

**Comment by oobi** [comment]
How does IceFilms determine whether you're a bot or a browser? UserAgent string or something similar?

**Comment by Kulendra** [comment]
@Eldorados Is there actually a way to fix it? I understand that you will not be able to give it out as part of your standard repo, but I would be happy to test it out.

**Comment by oobi** [comment]
I guess the thing to do to keep the file hosts happy would be to find some way to show their ads, thereby not depriving them of the revenue stream. I don't know how or if that would be possible. 

Shame - I like IceFilms but the plugin experience is far superior to wading through the website.

**Comment by Eldorados** [comment]
It can easily be fixed, but they can also easily update their site on a daily/hourly basis to keep blocking us out... none of us want to be constantly updating our code

They are holding strong in their stance regarding ads on the hosts, so we are looking into ways of dealing with that, once that is figured out and everyone is happy then I'll be updating the addon

If anyone tries sending out a fix to everyone then they will ruin it for us all, Icefilms will start banning ip's etc.. so let us figure out first, in the meantime everyone can use 1Channel, SALTS, Genesis

**Comment by hypes057** [comment]
I would totally watch an ad to use this plugin. I don't care I'd even watch a couple spread out like hulu does. Hope you can get it resolved with them and thanks for the excellent plugin and work.

**Comment by Kulendra** [comment]
Just an update, perhaps this is what @Eldorados meant that it can be easily fixed; I noticed that while watching Icefilms, that there is a popup advert that appears before the video is played. Could this help?

In a realistic sense it wouldn't serve the purpose as the ads are likely to be CPC as opposed to CPM. But who knows...

**Comment by Eldorados** [comment]
We're still trying to get a good solution that works, the ads are not
generating the impressions properly the way we like yet

So a little bit of work left to do

**Comment by daemeonzane** [comment]
I have a feeling this is the same as my issue, if you want to close it. Any ETA on the ads fix?

**Comment by Eldorados** [comment]
It's been fixed almost 2 weeks ago, latest version is 1.12.0
