### ISSUE TITLE
Error while using mysql

### ISSUE THREAD

**Issue by prabinsh** [Eldorados/eldorado-xbmc-addons#24]
When I configure mysql, I get the following error in kodi.log

 File "C:\Users\Prabin\AppData\Roaming\Kodi\addons\plugin.video.icefilms\resources\lib\db_utils.py", line 326, in init_database
                                                self.__execute('CREATE TABLE IF NOT EXISTS cache_data (name TEXT, value TEXT), PRIMARY KEY(name(250))')

This works perfectly after updating to 
self.__execute('CREATE TABLE IF NOT EXISTS cache_data (name TEXT, value TEXT, PRIMARY KEY(name(250)))')

Can this fix be included? Thanks

**Comment by Eldorados** [comment]
Thanks, thought I fixed this before, will be in next update

**Comment by prabinsh** [comment]
Thanks it works now.
