### ISSUE TITLE
Getting issue while connecting to imdb site

### ISSUE THREAD

**Issue by prabinsh** [Eldorados/eldorado-xbmc-addons#25]
Hello,
I started noticing that connection to imdb site is failing in log file

Error connecting to IMDB: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Can you please take a look at this?

**Comment by Eldorados** [comment]
IMDB api is no more, metahandlers has been updated to use OMDB instead, update will be out soon

**Comment by prabinsh** [comment]
Thanks
