### ISSUE TITLE
Error Accessing Any Title

### ISSUE THREAD

**Issue by daemeonzane** [Eldorados/eldorado-xbmc-addons#26]
I have the repo 2.0.2, and Icefilms addon version 1.12. When accessing any title after I opened the directory, I cannot proceed to the list of links.
In the instance below, I accessed Icefilms -> Movies -> A-Z -> U -> Underworld: Awakening. I removed Kodi, downloaded a fresh install, redownloaded the repo zip, and enaured everything updated prior to attempting to open a movie. 
Below is my log file: 
http://pastebin.com/xPeaaLpH

**Comment by Eldorados** [comment]
This is due to metahandlers using IMDB which is no more, new version of metahandlers will be out soon to fix this
